CREATE TABLE SECURITIES (assetNumber text PRIMARY KEY, 
         originalLoanAmount real,
         originalLoanTerm int,     
         scheduledPaymentAmount real,  
         interestRate real,
         reportingPeriodEndingDate text,
         originalFirstPaymentDate text, 
         underwritingIndicator int, 
         gracePeriodNumber int, 
         subvented text, 
         vehicleNewUsedCode int, 
         vehicleModelYear int,        
         vehicleValueAmount real,  
         obligorCreditScore int,        
         obligorIncomeVerificationLevelCode int,     
         obligorEmploymentVerificationCode int,        
         coObligorIndicator int, 
         paymentToIncomePercentage real,
         nextReportingPeriodPaymentAmountDue real,
         currentDelinquencyStatus int,
         reportingPeriodBeginningDate text,
         originatorName text,
         originationDate text,
         loanMaturityDate text,
         vehicleManufacturerName text,
         vehicleModelName text,
         reportingPeriodBeginningLoanBalanceAmount real,
         obligorGeographicLocation text
         );

